import './university.css';
const $=id=>document.getElementById(id), endpoint='https://cafecito-live-studio-2235-live.twil.io/state';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let token=sessionStorage.getItem('cafecito-presenter')||'', generation=0, timer, revision='', preview=false;
const cache=new Map();
function markup(id,html){if(cache.get(id)!==html){$(id).innerHTML=html;cache.set(id,html);}}
const label=s=>String(s||'waiting').replaceAll('_',' ');
function badge(id,text,good=false,bad=false){$(id).textContent=label(text);$(id).className='badge'+(good?' good':bad?' bad':'');}
function render(s){
 const key=s?`${s.id}:${s.revision}`:'empty';if(key===revision)return;revision=key;
 const u=s?.university||{}, verified=u.verification==='verified', done=u.reset==='completed';
 $('callStatus').textContent=s?.status==='active'?'● CALL ACTIVE':s?'CALL ENDED':'';
 $('agentState').textContent=s?.status==='ended'?'Conversation complete':({speaking:'Maya is speaking',thinking:'Checking the university desk',listening:'Listening to the caller'}[s?.agent_state]||'Your university AI assistant');
 $('studentId').textContent=u.student_id||'— — — — — — — —';
 badge('lookup',u.lookup||'waiting',u.lookup==='matched',u.lookup==='not_found');
 $('studentName').textContent=verified?u.student?.name:'Record locked';$('program').textContent=verified?u.student?.program:'Student details appear after the SMS check.';
 badge('resetBadge',u.reset||'locked',done);$('resetTitle').textContent=done?'Back on track.':verified?'Ready for confirmation.':'Verification comes first.';
 $('resetText').textContent=done?'Demo reset completed. No real university password was changed.':verified?'SMS reply checked. Maya asks the caller before completing the simulated reset.':'Once the reply is verified, Maya asks permission to complete the demo reset.';
 const sms=u.sms||'not_requested';badge('smsBadge',sms,verified,['failed','locked','expired','retry','superseded','opted_out'].includes(sms));
 $('smsTitle').textContent=verified?'Reply received. Check passed.':sms==='not_requested'?'Permission before a text.':['failed','undelivered','locked','expired','superseded','opted_out'].includes(sms)?'The check could not complete.':sms==='retry'?'A correction is needed.':'The conversation stays open.';
 $('smsText').textContent=verified?'The actual SMS reply matched a valid challenge and sample student ID.':sms==='not_requested'?'Maya asks to text the number the caller is using. The caller replies while staying on the line.':sms==='retry'?'Reply with the code from the SMS, a space, and a sample student ID.':`SMS ${label(sms)}${u.destination?' · '+u.destination:''}. Maya checks for the reply while the caller stays on the line.`;
 $('smsHint').textContent=preview?'SCRIPTED PREVIEW · No message is sent.':'Real SMS. Short-lived check. No passwords collected.';
 [!!u.student_id,sms!=='not_requested',verified,done].forEach((v,i)=>$('step'+(i+1)).classList.toggle('done',v));
 const box=$('transcript'), near=box.scrollHeight-box.scrollTop-box.clientHeight<70;
 markup('transcript',s?.transcripts?.length?s.transcripts.map(t=>`<div class="message ${t.role==='user'?'user':''}"><small>${t.role==='user'?'CALLER':'MAYA'}</small><p>${esc(t.text)}</p></div>`).join(''):'<div class="empty"><h3>One call. A way back in.</h3><p>Live captions appear here as the caller and Maya speak.</p></div>');if(near)box.scrollTop=box.scrollHeight;
 markup('events',s?.events?.length?[...s.events].reverse().map(e=>`<div class="event"><strong>${esc(e.title)}</strong><time>${new Date(e.at).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</time><p>${esc(e.detail)}</p></div>`).join(''):'<p class="placeholder">Each step appears here as it happens.</p>');
}
function stop(){generation++;clearTimeout(timer);}
async function request(){const response=await fetch(endpoint,{method:'POST',body:new URLSearchParams({presenter_key:token,use_case:'university',call:$('calls').value}),signal:AbortSignal.timeout(10000)});if(!response.ok)throw Error(response.status===401?'Presenter key was not accepted.':'Live feed temporarily unavailable.');return response.json();}
function connect(){stop();preview=false;revision='';const gen=generation;async function poll(){try{const data=await request();if(gen!==generation)return;const chosen=$('calls').value;markup('calls','<option value="">Follow newest university call</option>'+data.calls.map(c=>`<option value="${esc(c.id)}">${esc(c.name)} · ${new Date(c.started_at).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})} · ${esc(c.status)}</option>`).join(''));$('calls').value=chosen;render(data.session);$('connection').textContent=data.session?'LIVE CLOUD FEED':'CONNECTED · WAITING FOR A UNIVERSITY CALL';$('connect').textContent='● Connected';}catch(e){if(gen!==generation)return;$('connection').textContent=e.message;}if(gen===generation)timer=setTimeout(poll,1200);}poll();}
$('connect').onclick=()=>token?connect():$('access').showModal();$('cancelAccess').onclick=()=>$('access').close();
$('accessForm').onsubmit=async e=>{e.preventDefault();token=$('key').value.trim();try{await request();sessionStorage.setItem('cafecito-presenter',token);$('key').value='';$('access').close();connect();}catch(err){$('error').textContent=err.message;}};
$('calls').onchange=connect;$('lock').onclick=()=>{stop();token='';sessionStorage.removeItem('cafecito-presenter');preview=false;revision='';render(null);$('connection').textContent='PRESENTER VIEW LOCKED';$('connect').textContent='Connect live';};
$('playbook').onclick=()=>$('guide').showModal();$('closeGuide').onclick=()=>$('guide').close();
$('rehearse').onclick=()=>{stop();preview=true;revision='';$('connection').textContent='SCRIPTED PREVIEW · NO SMS SENT';$('connect').textContent='Connect live';const gen=generation;
 const s={id:'preview',revision:0,status:'active',agent_state:'speaking',transcripts:[],events:[],university:{sms:'not_requested',verification:'unverified',reset:'locked'}};
 const say=(role,text)=>s.transcripts.push({role,text});const event=(title,detail)=>s.events.push({title,detail,at:Date.now()});
 const steps=[()=>{say('assistant',"Welcome to Cafecito University password-reset automation. I'm Maya, your AI assistant. Do you have your student ID handy?");event('Call connected','Scripted preview — no real SMS is sent.');},()=>{say('user','Yes, I have it.');say('assistant','What’s your student ID?');},()=>{say('user','99999999');Object.assign(s.university,{student_id:'99999999',lookup:'not_found'});event('Student ID not found','99999999');say('assistant','That didn’t match. May I send a text to the number you’re calling from?');},()=>{say('user','Yes, please.');s.university.sms='queued';event('SMS submitted','Preview only');say('assistant','A text is on its way. Reply with its code and your student ID. I’ll stay on the line.');},()=>{s.university.sms='delivered';event('Waiting for SMS reply','The call remains open.');},()=>{Object.assign(s.university,{student_id:'M123497',lookup:'matched',sms:'reply_received',verification:'verified',student:{name:'Nelson Medina',program:'Business Administration'},reset:'ready'});event('SMS reply verified','Sample student record unlocked.');say('assistant','Thanks, Nelson. Your reply checked out. Shall I complete the demo reset?');},()=>{say('user','Yes, go ahead.');s.university.reset='completed';event('Demo reset completed','No actual account changed.');say('assistant','The demo reset is complete. No real password was changed. Anything else I can help with?');},()=>{s.status='ended';event('Preview complete','Connect live and call to try real SMS.');}];let index=0;function next(){if(gen!==generation)return;steps[index++]();s.revision++;render(s);if(index<steps.length)timer=setTimeout(next,3500);}next();};
render(null);if(token)connect();
